config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/help', to: 'welcome#help', via: 'get'
  match '/faq', to: 'welcome#faq', via: 'get'
  match '/proposal', to: 'welcome#proposal', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/activate/:activation_token', to: 'users#activate_user', via: 'get', as: 'activate'
  match '/resend_activation_email', to: 'users#resend_activation_email', via: 'post'

  match '/profile', to: 'users#show', via: 'get'

  match '/profile/edit', to: 'users#edit', via: 'get'
  match '/profile/edit', to: 'users#update', via: 'post'

  match '/profile/edit/email', to: 'users#edit_email', via: 'get'
  match '/profile/edit/email', to: 'users#update_email', via: 'post'

  match '/profile/edit/password', to: 'users#edit_password', via: 'get'
  match '/profile/edit/password', to: 'users#update_password', via: 'post'

  match '/forgot_password', to: 'users#forgot_password', via: 'get'
  match '/reset_password', to: 'users#reset_password', via: 'post'

  match '/proposal/new', to: 'proposals#new', via: 'get'
  match '/proposal/:proposal_id/reply', to: 'proposals#reply', via: 'get', as: 'reply_proposal'
  match '/proposal/:proposal_id/reply', to: 'proposals#update_reply', via: 'post'
  match '/proposal/:proposal_id/delete', to: 'proposals#destroy', via: 'delete', as: 'delete_proposal'

  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]
  resources :proposals, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :proposals
  before_save { self.mysnu = mysnu.downcase }
  before_create :create_remember_token
  before_create :create_activation_token

  validates :name, presence: true,
                   length: { maximum: 20 },
                   uniqueness: { case_sensitive: false }
  validates :mysnu, presence: true,
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password_digest, presence: true

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_activation_token
      self.activation_token = User.encrypt(User.new_remember_token)
    end

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_signed_in_user, only: [:new, :create, 
                                            :forgot_password, :reset_password]
  before_action :signed_in_user, only: [:show, :edit, :update,
                                        :edit_password, :update_password,
                                        :edit_email, :update_email]
  before_action :admin_user, only: [:index, :destroy]

  # Show All Users
  # Requires admin permission
  def index
    @users = User.all
  end

  # Show User Information
  # User Profile
  def show
    @user = current_user
  end

  # Sign Up
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Success

      # Auto Login
      sign_in @user

      # Send Activation Email
      send_activation_email(@user)

      # Flash Message
      flash[:success] = "회원가입이 정상적으로 완료되었습니다."
      redirect_to profile_path
    else
      # Failed
      flash[:error] = "회원가입에 실패했습니다. 계속되는 경우 관리자에게 문의하세요."
      render 'new'
    end
  end

  def resend_activation_email
    @user = current_user

    send_activation_email(@user)
    flash[:success] = "인증 이메일이 재발송되었습니다."
    redirect_to profile_path
  end

  def activate_user
    activation_token = params[:activation_token]
    @user = User.find_by(activation_token: activation_token)

    # User should not be nil
    if @user && @user.update_attributes(active: true)
      # Success
      flash[:success] = "이메일 인증이 성공적으로 되었습니다."
      redirect_to profile_path
    else
      # Failed
      render root_path
    end
  end

  def edit
    # Edit User Basic informations
    # Except Password and Email
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      # Success
      flash[:success] = "Edit!"
      redirect_to profile_path
    else
      # Failed
      render 'edit'
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_attributes(user_params)
      # Success
      flash[:success] = "새로운 패스워드로 변경되었습니다. 다시 로그인해주세요."
      sign_out
      redirect_to signin_path
    else
      # Failed
      render 'edit_password'
    end
  end

  def edit_email
    @user = current_user
  end

  def update_email
    @user = current_user
    if @user.update_attributes(user_params)
      # Success
      flash[:success] = "새로운 마이스누 아이디로 변경되었습니다. 인증 메일이 발송되었습니다."
      @user.update_attributes(activation_token: User.encrypt(User.new_remember_token))
      @user.update_attributes(active: false)
      send_activation_email(@user)
      redirect_to profile_path
    else
      # Failed
      render 'edit_email'
    end
  end

  def forgot_password
  end

  def reset_password
    @user = User.find_by(mysnu: user_params[:mysnu])
    new_password = random_string_size_of(8)
    @user.update_attributes(password: new_password,
                            password_confirmation: new_password)
    send_password_reset_email(@user, new_password)
    redirect_to root_path
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :mysnu, :password, :password_confirmation)
    end

    def send_activation_email(user)
      UserMailer.activation_email(@user).deliver
    end

    def send_password_reset_email(user, password)
      UserMailer.password_reset_email(user, password).deliver
    end

    # Before Filters

    def corrent_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>
<%= form_for :user do |f| %>
  <div>
  <%= f.label :name  %><br />
  <%= f.text_field :name  %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit_email.html.erb
<h1>Edit Email</h1>
<p>Email을 변경하게 되면 새로운 이메일로 재인증하셔야 합니다.</p>
<p>동의하시면 계속 진행하세요.</p>

<%= form_for :user, url: profile_edit_email_path do |f| %>
  <div>
  <%= f.label :mysnu %><br />
  <%= f.text_field :mysnu %>@snu.ac.kr<br />
  </div>
  <div>
  <%= f.submit  %>
  </div>
<% end %>

app/views/users/edit_password.html.erb
<h1>Edit Password</h1>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg  %>
    <% end %>
  </ul>
<% end %>

<%= form_for :user, url: profile_edit_password_path do |f|  %>
  <div>
  <%= f.label :password  %><br />
  <%= f.password_field :password  %>
  </div>

  <div>
  <%= f.label :password_confirmation  %><br />
  <%= f.password_field :password_confirmation %>
  </div>

  <div>
  <%= f.submit  %>
  </div>
<% end %>

app/views/users/forgot_password.html.erb
<h1>forgot password?</h1>
<p>암호는 DB에 암화화되어 저장되어 복구할 수 없습니다.
마이스누 아이디를 입력해주시면 새로운 암호를 생성하여 보내드립니다.</p>

<%= form_for :user, url: reset_password_path do |f|  %>
  <div>
  <%= f.label :mysnu  %><br />
  <%= f.text_field :mysnu  %>@snu.ac.kr
  </div>

  <div>
  <%= f.submit "Reset Password" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ol>
  <% @users.each do |user|  %>
    <li><%= user.name  %></li>
  <% end %>
</ol>

app/views/users/new.html.erb
<section id="box-sign">
  <div class="container">
      <div class="row">
          <div class="box">
              <div class="head">
                  <h6>Create your account</h6>
              </div>

              <div class="form">
                  <%= form_for @user do |f| %>
                      <div class="form-group clearfix">
                          <div class="col-lg-12">
                            <%= f.text_field :mysnu, class: "form-control", placeholder: "마이스누 아이디" %>@snu.ac.kr
                          </div>
                      </div>
                      <div class="form-group clearfix">
                          <div class="col-lg-12">
                            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
                          </div>
                        </div>
                      <div class="form-group clearfix">
                          <div class="col-lg-12">
                            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
                          </div>
                        </div>
                      <div class="form-group clearfix">
                          <div class="col-lg-12">
                            <%= f.submit "회원가입", class: "btn btn-gray" %>
                          </div>
                      </div>
                    <% end %>
              </div>
          </div>
          <p class="already">이미 스누챗 계정을 가지고 있으신가요??<a href="<%= signin_url  %>">로그인</a></p>
      </div>
  </div>
</section>

app/views/users/show.html.erb
<section id="about">
    <div class="inner-block">
        <div class="container">
            <header>
                <h2>프로필</h2>
                <span class="line"></span>
            </header>

            <% if !@user.active %>
              <div class="alert alert-danger alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong>이메일 인증이 되지 않았습니다.</strong><br />
              서비스를 정상적으로 이용하기 위해서는 마이스누 웹메일을 통한 인증이 필요합니다.
              이메일을 받지 못하신 경우 <%= link_to "재발송", resend_activation_email_path, method: :post  %> 링크를 클릭해주세요.
              </div>
            <% else %>
              <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong>당신은 상대방을 배려하는 좋은 사용자입니다.</strong><br />
              </div>
            <% end %>

            <div class="row intro">
                <div class="col-lg-12">
                    <h3>
                    </h3>
                </div>
            </div>

            <div class="row text">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <p>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>