config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/help', to: 'welcome#help', via: 'get'
  match '/faq', to: 'welcome#faq', via: 'get'
  match '/proposal', to: 'welcome#proposal', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/activate/:activation_token', to: 'users#activate_user', via: 'get', as: 'activate'
  match '/resend_activation_email', to: 'users#resend_activation_email', via: 'post'

  match '/profile', to: 'users#show', via: 'get'

  match '/profile/edit', to: 'users#edit', via: 'get'
  match '/profile/edit', to: 'users#update', via: 'post'

  match '/profile/edit/email', to: 'users#edit_email', via: 'get'
  match '/profile/edit/email', to: 'users#update_email', via: 'post'

  match '/profile/edit/password', to: 'users#edit_password', via: 'get'
  match '/profile/edit/password', to: 'users#update_password', via: 'post'

  match '/forgot_password', to: 'users#forgot_password', via: 'get'
  match '/reset_password', to: 'users#reset_password', via: 'post'

  match '/proposal/new', to: 'proposals#new', via: 'get'
  match '/proposal/:proposal_id/reply', to: 'proposals#reply', via: 'get', as: 'reply_proposal'
  match '/proposal/:proposal_id/reply', to: 'proposals#update_reply', via: 'post'
  match '/proposal/:proposal_id/delete', to: 'proposals#destroy', via: 'delete', as: 'delete_proposal'

  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]
  resources :proposals, only: [:create]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # Home ( root_path )
  def index
  end

  # About Page
  def about
  end

  # Help Page
  def help
  end

  def faq
    @faqs = Faq.all
  end

  def proposal
    @proposals = Proposal.where(answer: false)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<section id="features-wrapper">
    <div class="container">
        <!-- features 1 -->
        <div class="inner-block features1">
            <header>
                <h2>서울대학교 소통 커뮤니티, 스누챗</h2>
                <span class="line"></span>
            </header>

            <div class="row">
                <div class="col-lg-12">
                    <h3 class="intro">
                      조금은 더 솔직하고, 조금은 더 발칙한 이야기들<br />
                      스누챗은 당신을 위한 서비스입니다.<br />
                      현재 다음과 같은 기능들이 제공되고 있습니다.
                    </h3>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4 feature">
                    <img src="<%= asset_path "feature1.jpg"  %>" alt="feature1" class="img-responsive thumb" />
                    <h3>
                        <i class="icon-cloud-upload"></i> 스누챗
                    </h3>
                    <p class="description">
                      스누챗이 사라졌다고요? 이제는 새로운 스누챗팅을 이용해보는건 어떨까요?
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature">
                    <img src="<%= asset_path "feature2.jpg"  %>" alt="feature2" class="img-responsive thumb" />
                    <h3>
                        <i class="icon-signal"></i> 스누밤부
                    </h3>
                    <p class="description">
                      페이스북에서 운영하는 대나무숲이요? 이제는 스누챗에서 한번에 확인하세요.
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature">
                    <img src="<%= asset_path "feature3.jpg"  %>" alt="feature3" class="img-responsive thumb" />
                    <h3>
                        <i class="icon-mobile-phone"></i> 에스크스누
                    </h3>
                    <p class="description">
                      "23살 여자 질문받아요.", "30살 마법사 질문받습니다." 등 질문에 최적화된 서비스 스누퀘스쳔?
                    </p>
                </div>
            </div>
        </div>

        <!-- features 2 -->
        <div class="inner-block features2">
            <header>
                <h2>다양한 기능 지원</h2>
                <span class="line"></span>
            </header>

            <div class="row">
                <div class="col-lg-12">
                    <h3 class="intro">
                      스누챗은 다양한 기능을 지원합니다.
                    </h3>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-cloud-upload"></i>
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-wrench"></i>
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-signal"></i>
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-lock"></i>
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-mobile-phone"></i> 
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 feature2">
                    <div class="icon">
                        <i class="icon-beaker"></i>
                    </div>
                    <h4>Many desktop publishing editor these available</h4>
                    <p>
                        You can't do better design with a computer, but you can speed up your work
                        enormously.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/welcome/faq.html.erb
<section id="faq">
    <div class="container">
        <div class="inner-block">
            <header>
                <h2>자주 묻는 질문들</h2>
                <span class="line"></span>
            </header>

            <% @faqs.each do |faq| %>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel-group" id="accordion">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + faq.id.to_s %>">
                              <%= faq.title %>
                            </a>
                          </h4>
                        </div>
                        <div id="<%= "collapse" + faq.id.to_s  %>" class="panel-collapse collapse">
                          <div class="panel-body">
                              <%= faq.content  %>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</section>

app/views/welcome/index.html.erb
<!-- Banner -->
<section class="banner">
  <div class="container">
    <div class="row">
      <h1>서울대생을 실시간 익명 채팅 커뮤니티 <span>스누챗 </span>에 오신 것을 환영합니다.</h1>

      <div class="img">
        <img class="img-responsive" src="<%= asset_path 'devices.png' %>">
      </div>
    </div>	
  </div>
</section>

app/views/welcome/proposal.html.erb
<section id="faq">
    <div class="container">
        <div class="inner-block">
            <header>
                <h2>한줄 제안하기</h2>
                <span class="line"></span>
            </header>

            <div>
              <%= form_for :proposal, url: proposals_path do |f|  %>
                <%= f.text_area :content, class: "form-control" %>
                <%= f.submit "제안 날리기", class: "btn btn-gray"  %>
              <% end %>
            </div>

            <div id="proposal_table">
            <% @proposals.reverse.each do |proposal| %>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel-group" id="accordion">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + proposal.id.to_s %>">
                              <%= proposal.content %>
                              <% if proposal.answers.any? %>
                                <span class="label label-success pull-right">답변완료</span>
                              <% else %>
                                <span class="label label-danger pull-right">미답변</span>
                              <% end %>
                            </a>
                          </h4>
                        </div>
                        <div id="<%= "collapse" + proposal.id.to_s  %>" class="panel-collapse collapse">
                          <div class="panel-body">
                            <% if proposal.answers.any? %>
                              <%= proposal.answers.first.content  %>
                            <% else %>
                              개발자의 답변을 기다리고 있습니다.
                              <% if current_user.admin? %>
                                <%= link_to "reply", reply_proposal_path(proposal_id: proposal.id) %>
                                <%= link_to "delete", delete_proposal_path(proposal_id: proposal.id), method: :delete %>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <% end %>
            </div>
        </div>
    </div>
</section>