config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/help', to: 'welcome#help', via: 'get'
  match '/faq', to: 'welcome#faq', via: 'get'
  match '/proposal', to: 'welcome#proposal', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/activate/:activation_token', to: 'users#activate_user', via: 'get', as: 'activate'
  match '/resend_activation_email', to: 'users#resend_activation_email', via: 'post'

  match '/profile', to: 'users#show', via: 'get'

  match '/profile/edit', to: 'users#edit', via: 'get'
  match '/profile/edit', to: 'users#update', via: 'post'

  match '/profile/edit/email', to: 'users#edit_email', via: 'get'
  match '/profile/edit/email', to: 'users#update_email', via: 'post'

  match '/profile/edit/password', to: 'users#edit_password', via: 'get'
  match '/profile/edit/password', to: 'users#update_password', via: 'post'

  match '/forgot_password', to: 'users#forgot_password', via: 'get'
  match '/reset_password', to: 'users#reset_password', via: 'post'

  match '/proposal/new', to: 'proposals#new', via: 'get'
  match '/proposal/:proposal_id/reply', to: 'proposals#reply', via: 'get', as: 'reply_proposal'
  match '/proposal/:proposal_id/reply', to: 'proposals#update_reply', via: 'post'
  match '/proposal/:proposal_id/delete', to: 'proposals#destroy', via: 'delete', as: 'delete_proposal'

  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]
  resources :proposals, only: [:create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>서울대학교 실시간 채팅 서비스</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Style -->
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>

  <!--[if lt IE 9]>
    <script src="../../assets/js/html5shiv.js"></script>
    <script src="../../assets/js/respond.min.js"></script>
  <![endif]-->
  <!--[if IE 7]>
  <link rel="stylesheet" href="css/font-awesome-ie7.min.css">
  <![endif]-->
</head>
<body>
	<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
	  <div class="container">
	    <div class="navbar-header">
	      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
        <a href="<%= root_url  %>" class="navbar-brand " data-section="">
          <img src="<%= asset_path 'logo.png'  %>">
	      </a>
	    </div>

	    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
	      	<ul class="nav navbar-nav">
		        <li>
            <a href="<%= about_url  %>" class="" data-section="">스누챗</a>
		        </li>
		        <li>
            <a href="<%= about_url  %>" class="" data-section="">스누밤부</a>
		        </li>
		        <li>
            <a href="<%= about_url  %>" class="" data-section="">에스크스누</a>
		        </li>
		        <li>
            <a href="<%= faq_url  %>" class="" data-section="">자주 묻는 질문</a>
		        </li>
		        <li>
            <a href="<%= proposal_url  %>" class="" data-section="">한줄 제인하기</a>
		        </li>
		        <li>
            <a href="<%= help_url  %>" class="" data-section="">도움이 필요하신가요?</a>
		        </li>
	      	</ul>

          <ul class="nav navbar-nav pull-right">
            <% if signed_in? %>
            <li class="sign-btn">
              <a href="<%= profile_url  %>">프로필</a>
            </li>
            <li class="sign-btn">
              <%= link_to "로그아웃", signout_path, method: :delete  %>
            </li>

            <% else %>
            <li class="sign-btn">
              <a href="<%= signup_url  %>">회원가입</a>
            </li>
            <li class="sign-btn">
              <a href="<%= signin_url  %>">로그인</a>
            </li>
          </ul>
            <% end %>
	    </nav>
	  </div>
	</header>

  <%= yield %>
  <%= debug(params)  %>


	<!-- Footer -->
	<footer id="contact">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
					<a href="#">
            <img class="img-responsive" src="<%= asset_path 'logo.png'  %>">
					</a>

					<ul>
						<li>서울대학교 동문을 위한</li>
						<li>서울대학교 실시간 익명 채팅 커뮤니티</li>
						<li>스누챗 2014</li>
						<li class="phone">developed by @dobestan</li>
						<li><a href="#">dobestan@gmail.com</a></li>
					</ul>
				</div>

				<div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 pull-right">
					<h2>Contact Us</h2>
					<form>
						<div class="col-sm-6 col-md-6 col-lg-6">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Name">
							</div>
							<div class="form-group">
								<input type="email" class="form-control" placeholder="Email">
							</div>
							<div class="form-group">
								<input type="text" class="form-control" placeholder="City">
							</div>
						</div>

						<div class="col-sm-6 col-md-6 col-lg-6">
							<div class="form-group">
								<textarea class="form-control" rows="6" placeholder="Comment"></textarea>
							</div>
						</div>
						<button type="submit" class="btn btn-green">Send</button>
					</form>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4">
					<p>Copyright 2014 SnuChat | All Rights Reserved</p>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>